### PR TITLE
Add support for STS

### PR DESCRIPTION
**Pull request by mbakerbp**

### CODE REVIEW

**Comment by cobbzilla** [comment]
nice, simple and clean. if you fixup the braces/indentation to match the code style, I will happily merge.

**Comment by mbakerbp** [comment]
@cobbzilla on it now ;) it was doen as one of our staff was having issues with it!

**Comment by mbakerbp** [comment]
@cobbzilla Hows that one :)

**Comment by cobbzilla** [comment]
beautiful @mbakerbp -- thanks.

**Pull request merged**
