### PR TITLE
Ability to Use Jar as a Library Bundled in Other Tools

### PR DESCRIPTION
**Pull request by kylec32**
There will be merge conflicts between this and my earlier PR https://github.com/cobbzilla/s3s3mirror/pull/112 they will be easy enough to fix after the first one gets merged. Wanted to open the PR now though to start the conversation.

The PR adds the ability to call this jar from another Java library (via BucketMirrorMaker). This library, in it's form before the PR, was very focused on being driven via the command line with all output going out via that interface. This makes sense with how it's been used before; however, my goal has been to bundle this library as just part of a larger tool. 

This change creates an easy entry point that handles being called via something other than MirrorMain. It also creates a way to get the results of the copy at the end of the copy as well as periodically during the copy.

To be of the most utility this library would also be deployed to a public maven repository as a non-uber jar but that would likely be a chunk of work for you and I should be able to work around it for my use case. 

A bare minimum usage of this could look something like:
```java
  BucketMirrorMaker mirrorMaker = new BucketMirrorMaker();

  MirrorOptions options = MirrorOptions.builder()
                                       .source("kcarter-source")
                                       .destination("kcarter-target")
                                       .detailedErrorLogging(true)
                                       .statusListener(new ExampleStatusListener())
                                       .syncStrategy(SyncStrategy.SIZE_LAST_MODIFIED)
                                       .build();

  MirrorStats stats = mirrorMaker.makeCopy(options);

  System.out.println("Done:");
  System.out.println(stats);
  System.out.println("Error copies:");
  System.out.println(stats.getFailedCopies());
  System.out.println("Error delete:");
  System.out.println(stats.getFailedDeletes());
```

```java
public class ExampleStatusListener implements StatusListener {
    @Override
    public Duration getUpdateInterval() {
        return Duration.ofSeconds(10);
    }

    @Override
    public void provideStatus(MirrorStats mirrorStats) {
        System.out.println(mirrorStats);
    }
}
```

### CODE REVIEW

**Comment by cobbzilla** [comment]
@kylec32 This is a very welcome improvement. You are right that the impetus for s3s3mirror was a better command-line tool. I agree that library-izing it would make it much more useful, and I really like this PR.

I can easily change the maven pom.xml so that the default build is a non-uber jar that can be published to a maven repo, we can retain the uberjar as a separate maven profile.

**Comment by kylec32** [comment]
That sounds great. It currently does create a non-uber jar version as well as the uber jar, the missing piece to making it most useful is the hosting of the jar on a public maven repository. 

Thanks for taking a look so quickly.

**Comment by cobbzilla** [comment]
@kylec32 I looked into it, and publishing to maven central will be [a bit involved](https://dev.to/bobman38/beginner-guide-to-maven-central-publishing-3jio), I won't have time to get to it for a while. In the meantime I think we can use [jitpack](https://jitpack.io/) to pull in s3s3mirror as a maven dependency.

**Comment by kylec32** [comment]
I had heard the name jitpack before but never seen what it did, great call out, that hits the requirement exactly for me. Thank you! 

I have merged the latest change of 2.1-stable into this branch, upped the version, and create a new maven profile to handle the uber jar. So now if you do a regular build you get a non-uber jar, if you pass the profile `uberjar` it will build the uberjar for CLI consumption.

**Comment by cobbzilla** [comment]
Merged this and created https://github.com/cobbzilla/s3s3mirror/issues/114 to make things easier for novice users.

**Pull request merged**
